/**
 * Catalog for جزارا الراجي: categories, SKUs, fridge sources, slaughter templates.
 * Prices are placeholders (EGP) — merchant should update in the product form.
 */

const kg = (name, extra = {}) => ({ name, price: extra.price ?? 300, netPrice: extra.netPrice ?? 250, stock: extra.stock ?? 0, ...extra });
const piece = (name, extra = {}) => ({ name, price: extra.price ?? 50, netPrice: extra.netPrice ?? 30, stock: extra.stock ?? 0, ...extra });

export const AL_RAJI_STORE_FLAGS = {
  weightSalesEnabled: true,
  cutFromSourceEnabled: true,
  businessActivityType: 'butcher',
};

export const AL_RAJI_CATEGORIES = [
  {
    code: 'KANDOUZ',
    name: 'كندوز',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { skuKey: 'kandouz_fridge', name: 'كندوز ثلاجة', isSource: true, price: 310, netPrice: 265, stock: 0 },
      { skuKey: 'kandouz_half', name: 'نصف عجل كندوز', sourceKey: 'kandouz_fridge', price: 310, netPrice: 265 },
      { skuKey: 'kandouz_quarter', name: 'ربع عجل كندوز', sourceKey: 'kandouz_fridge', price: 310, netPrice: 265 },
      { skuKey: 'kandouz_bone_in', name: 'لحم كندوز بالعظم', sourceKey: 'kandouz_fridge', price: 320, netPrice: 265 },
      { skuKey: 'kandouz_fatty', name: 'لحم كندوز ملبس', sourceKey: 'kandouz_fridge', price: 330, netPrice: 270 },
      { skuKey: 'kandouz_sura', name: 'صرة كندوز', sourceKey: 'kandouz_fridge', price: 300, netPrice: 250 },
      { skuKey: 'kandouz_dosh', name: 'دوش كندوز', sourceKey: 'kandouz_fridge', price: 305, netPrice: 255 },
      { skuKey: 'kandouz_sinn', name: 'سن كندوز', sourceKey: 'kandouz_fridge', price: 315, netPrice: 260 },
      { skuKey: 'kandouz_moza', name: 'موزة كندوز', sourceKey: 'kandouz_fridge', price: 300, netPrice: 250 },
      { skuKey: 'kandouz_entrecote', name: 'إنتركوت', sourceKey: 'kandouz_fridge', price: 390, netPrice: 280 },
      { skuKey: 'kandouz_kebab_halla', name: 'كباب حلة', sourceKey: 'kandouz_fridge', price: 340, netPrice: 265 },
      { skuKey: 'kandouz_veg_cubes', name: 'مكعبات خضار', sourceKey: 'kandouz_fridge', price: 330, netPrice: 260 },
      { skuKey: 'kandouz_steak', name: 'ستيك', sourceKey: 'kandouz_fridge', price: 400, netPrice: 290 },
      { skuKey: 'kandouz_boftek', name: 'بفتيك', sourceKey: 'kandouz_fridge', price: 420, netPrice: 290 },
      { skuKey: 'kandouz_filetto', name: 'فليتو', sourceKey: 'kandouz_fridge', price: 450, netPrice: 320 },
      { skuKey: 'kandouz_rosto', name: 'روستو', sourceKey: 'kandouz_fridge', price: 380, netPrice: 280 },
      { skuKey: 'kandouz_prime', name: 'لحم قطعيات صافي', sourceKey: 'kandouz_fridge', price: 400, netPrice: 290 },
      { skuKey: 'kandouz_top_round', name: 'وش فخدة', sourceKey: 'kandouz_fridge', price: 370, netPrice: 275 },
      { skuKey: 'kandouz_boush', name: 'بوش كندوز', sourceKey: 'kandouz_fridge', price: 180, netPrice: 140 },
      { skuKey: 'kandouz_fat', name: 'دهن كندوز', sourceKey: 'kandouz_fridge', price: 80, netPrice: 50 },
      { skuKey: 'kandouz_mince_fatty', name: 'مفروم دسم', sourceKey: 'kandouz_fridge', price: 320, netPrice: 260 },
      { skuKey: 'kandouz_mince_lean', name: 'مفروم صافي', sourceKey: 'kandouz_fridge', price: 340, netPrice: 270 },
      {
        skuKey: 'kandouz_masoura',
        name: 'ماسورة كندوز',
        sellByWeightOverride: false,
        price: 50,
        netPrice: 30,
        stock: 0,
      },
    ],
  },
  {
    code: 'DHANI',
    name: 'ضاني',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { skuKey: 'dhani_fridge', name: 'ضاني ثلاجة', isSource: true, price: 400, netPrice: 350, stock: 0 },
      { skuKey: 'dhani_half', name: 'نصف ذبيحة ضاني', sourceKey: 'dhani_fridge', price: 400, netPrice: 350 },
      { skuKey: 'dhani_quarter', name: 'ربع ذبيحة ضاني', sourceKey: 'dhani_fridge', price: 400, netPrice: 350 },
      { skuKey: 'dhani_neck', name: 'رقبة ضاني', sourceKey: 'dhani_fridge', price: 380, netPrice: 330 },
      { skuKey: 'dhani_dosh', name: 'دوش ضاني', sourceKey: 'dhani_fridge', price: 390, netPrice: 340 },
      { skuKey: 'dhani_shoulder', name: 'زند ضاني', sourceKey: 'dhani_fridge', price: 410, netPrice: 350 },
      { skuKey: 'dhani_leg', name: 'فخدة ضاني', sourceKey: 'dhani_fridge', price: 450, netPrice: 390 },
      { skuKey: 'dhani_ribs', name: 'ريش ضاني', sourceKey: 'dhani_fridge', price: 480, netPrice: 400 },
      { skuKey: 'dhani_loin', name: 'بيت كلاوي ضاني', sourceKey: 'dhani_fridge', price: 470, netPrice: 400 },
      { skuKey: 'dhani_boneless', name: 'ضاني مشفي', sourceKey: 'dhani_fridge', price: 460, netPrice: 390 },
    ],
  },
  {
    code: 'BETLO',
    name: 'بتلو',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { skuKey: 'betlo_fridge', name: 'بتلو ثلاجة', isSource: true, price: 360, netPrice: 310, stock: 0 },
      { skuKey: 'betlo_half', name: 'نصف عجل بتلو', sourceKey: 'betlo_fridge', price: 360, netPrice: 310 },
      { skuKey: 'betlo_quarter', name: 'ربع عجل بتلو', sourceKey: 'betlo_fridge', price: 360, netPrice: 310 },
      { skuKey: 'betlo_neck', name: 'رقبة بتلو', sourceKey: 'betlo_fridge', price: 340, netPrice: 290 },
      { skuKey: 'betlo_dosh', name: 'دوش بتلو', sourceKey: 'betlo_fridge', price: 345, netPrice: 295 },
      { skuKey: 'betlo_shoulder', name: 'زند بتلو', sourceKey: 'betlo_fridge', price: 350, netPrice: 300 },
      { skuKey: 'betlo_leg', name: 'فخدة بتلو', sourceKey: 'betlo_fridge', price: 370, netPrice: 315 },
      { skuKey: 'betlo_ribs', name: 'ريش بتلو', sourceKey: 'betlo_fridge', price: 390, netPrice: 330 },
      { skuKey: 'betlo_loin', name: 'ريش بيت كلاوي بتلو', sourceKey: 'betlo_fridge', price: 400, netPrice: 340 },
      { skuKey: 'betlo_shank_bone', name: 'موزة بتلو بالعظم', sourceKey: 'betlo_fridge', price: 330, netPrice: 280 },
      { skuKey: 'betlo_shank', name: 'موزة بتلو', sourceKey: 'betlo_fridge', price: 350, netPrice: 300 },
      { skuKey: 'betlo_kebab', name: 'كباب حلة بتلو', sourceKey: 'betlo_fridge', price: 355, netPrice: 305 },
      { skuKey: 'betlo_boftek', name: 'بفتيك بتلو', sourceKey: 'betlo_fridge', price: 400, netPrice: 330 },
      { skuKey: 'betlo_boneless', name: 'بتلو مشفي', sourceKey: 'betlo_fridge', price: 390, netPrice: 330 },
    ],
  },
  {
    code: 'PROC_MEAT',
    name: 'مصنعات اللحوم',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { skuKey: 'proc_sausage', name: 'سجق', sourceKey: 'kandouz_fridge', price: 360, netPrice: 280 },
      { skuKey: 'proc_burger', name: 'برجر', sourceKey: 'kandouz_fridge', price: 350, netPrice: 270 },
      { skuKey: 'proc_kofta_skewer', name: 'كفتة سيخ', sourceKey: 'kandouz_fridge', price: 355, netPrice: 275 },
      { skuKey: 'proc_kofta_dawoud', name: 'كفتة داوود باشا', sourceKey: 'kandouz_fridge', price: 355, netPrice: 275 },
      { skuKey: 'proc_kofta_rice', name: 'كفتة أرز', sourceKey: 'kandouz_fridge', price: 340, netPrice: 265 },
      { skuKey: 'proc_kofta_pane', name: 'كفتة بانيه', sourceKey: 'kandouz_fridge', price: 360, netPrice: 275 },
      { skuKey: 'proc_shawarma_mar', name: 'شاورما لحمة متبل', sourceKey: 'kandouz_fridge', price: 370, netPrice: 280 },
      { skuKey: 'proc_boftek_mar', name: 'بفتيك متبل', sourceKey: 'kandouz_fridge', price: 430, netPrice: 295 },
      { skuKey: 'proc_hawawshi_mar', name: 'حواوشي متبل', sourceKey: 'kandouz_fridge', price: 350, netPrice: 270 },
      { skuKey: 'proc_hawawshi_mince', name: 'مفروم حواوشي متبل', sourceKey: 'kandouz_fridge', price: 345, netPrice: 268 },
      { skuKey: 'proc_fajita_mar', name: 'فاهيتا لحمة متبل', sourceKey: 'kandouz_fridge', price: 365, netPrice: 278 },
      { skuKey: 'proc_mombar_stuffed', name: 'ممبار محشي', sourceKey: 'kandouz_fridge', price: 280, netPrice: 200 },
      { skuKey: 'proc_tarb', name: 'طرب', sourceKey: 'kandouz_fridge', price: 380, netPrice: 290 },
    ],
  },
  {
    code: 'POULTRY',
    name: 'الدواجن',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { skuKey: 'chicken_baladi', name: 'فراخ بلدي ثلاجة', isSource: true, price: 95, netPrice: 82, stock: 0 },
      { skuKey: 'chicken_white', name: 'فراخ أبيض ثلاجة', isSource: true, price: 85, netPrice: 72, stock: 0 },
      { skuKey: 'chicken_pane', name: 'بانيه', sourceKey: 'chicken_white', price: 145, netPrice: 82 },
      { skuKey: 'chicken_shish', name: 'شيش طاووق', sourceKey: 'chicken_white', price: 150, netPrice: 85 },
      { skuKey: 'chicken_thigh', name: 'وراك', sourceKey: 'chicken_white', price: 110, netPrice: 75 },
      { skuKey: 'chicken_drum', name: 'دبوس', sourceKey: 'chicken_white', price: 100, netPrice: 70 },
      { skuKey: 'pigeon', name: 'حمام', isSource: true, price: 180, netPrice: 140, stock: 0 },
      { skuKey: 'duck', name: 'بط', isSource: true, price: 120, netPrice: 95, stock: 0 },
      { skuKey: 'rabbit', name: 'أرانب', isSource: true, price: 160, netPrice: 130, stock: 0 },
      { skuKey: 'turkey_breast', name: 'صدر رومي', isSource: true, price: 140, netPrice: 110, stock: 0 },
      { skuKey: 'turkey_thigh', name: 'وراك رومي', isSource: true, price: 120, netPrice: 95, stock: 0 },
      { skuKey: 'turkey_whole', name: 'ديك رومي', isSource: true, price: 110, netPrice: 90, stock: 0 },
      { skuKey: 'turkey_breast_boneless', name: 'صدور رومي مخلية', isSource: true, price: 155, netPrice: 120, stock: 0 },
    ],
  },
  {
    code: 'PROC_POULTRY',
    name: 'مصنعات الدواجن',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { skuKey: 'pp_pane_mar', name: 'بانيه متبل', sourceKey: 'chicken_white', price: 155, netPrice: 88 },
      { skuKey: 'pp_pane_grill', name: 'بانيه متبل شوي', sourceKey: 'chicken_white', price: 160, netPrice: 90 },
      { skuKey: 'pp_shish_mar', name: 'شيش طاووق متبل', sourceKey: 'chicken_white', price: 160, netPrice: 90 },
      { skuKey: 'pp_kofta', name: 'كفتة فراخ', sourceKey: 'chicken_white', price: 140, netPrice: 85 },
      { skuKey: 'pp_sausage', name: 'سجق فراخ', sourceKey: 'chicken_white', price: 145, netPrice: 88 },
      { skuKey: 'pp_burger', name: 'برجر فراخ', sourceKey: 'chicken_white', price: 140, netPrice: 85 },
      { skuKey: 'pp_chicken_mar', name: 'فراخ متبل', sourceKey: 'chicken_white', price: 120, netPrice: 80 },
      { skuKey: 'pp_shawarma', name: 'شاورما فراخ متبل', sourceKey: 'chicken_white', price: 150, netPrice: 88 },
      { skuKey: 'pp_fajita', name: 'فاهيتا فراخ متبل', sourceKey: 'chicken_white', price: 150, netPrice: 88 },
    ],
  },
  {
    code: 'OFFAL',
    name: 'فواكه اللحوم',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { skuKey: 'offal_liver_kandouz', name: 'كبدة كندوز صافي', isSource: true, price: 180, netPrice: 140, stock: 0 },
      { skuKey: 'offal_liver_mixed', name: 'كبدة كندوز مشكلة', isSource: true, price: 160, netPrice: 125, stock: 0 },
      { skuKey: 'offal_heart', name: 'قلب كندوز', isSource: true, price: 90, netPrice: 70, stock: 0 },
      { skuKey: 'offal_kidney', name: 'كلاوي كندوز', isSource: true, price: 85, netPrice: 65, stock: 0 },
      { skuKey: 'offal_testicles', name: 'مخاصي', isSource: true, price: 120, netPrice: 90, stock: 0 },
      { skuKey: 'offal_heart_kidney', name: 'قلب وكلاوي مشكلة', isSource: true, price: 88, netPrice: 68, stock: 0 },
      { skuKey: 'offal_trotter_front', name: 'كوارع كندوز أمامي', isSource: true, price: 70, netPrice: 45, stock: 0 },
      { skuKey: 'offal_trotter', name: 'كوارع كندوز', isSource: true, price: 65, netPrice: 40, stock: 0 },
      { skuKey: 'offal_trotter_buffalo', name: 'كوارع جاموسي', isSource: true, price: 65, netPrice: 40, stock: 0 },
      { skuKey: 'offal_mombar', name: 'ممبار بلدي', isSource: true, price: 80, netPrice: 50, stock: 0 },
      { skuKey: 'offal_tripe', name: 'كرشة', isSource: true, price: 70, netPrice: 45, stock: 0 },
      { skuKey: 'offal_lung', name: 'فشة', isSource: true, price: 40, netPrice: 25, stock: 0 },
      { skuKey: 'offal_spleen', name: 'طحال', isSource: true, price: 50, netPrice: 30, stock: 0 },
      { skuKey: 'offal_head_meat', name: 'لحم راس', isSource: true, price: 90, netPrice: 60, stock: 0 },
      { skuKey: 'offal_casing', name: 'هانك سجق', isSource: true, price: 60, netPrice: 35, stock: 0 },
      { skuKey: 'offal_lamb_head', name: 'رأس ضاني', isSource: true, price: 80, netPrice: 50, stock: 0 },
      { skuKey: 'offal_liver_lamb', name: 'كبدة ضاني', isSource: true, price: 200, netPrice: 160, stock: 0 },
      { skuKey: 'offal_leya', name: 'لية ضاني', isSource: true, price: 90, netPrice: 60, stock: 0 },
      { skuKey: 'offal_caul', name: 'منديل طرب', isSource: true, price: 70, netPrice: 45, stock: 0 },
      { skuKey: 'offal_boush_lamb', name: 'بوش ضاني', isSource: true, price: 150, netPrice: 110, stock: 0 },
      { skuKey: 'offal_bone_lamb', name: 'عظم ضاني', isSource: true, price: 25, netPrice: 10, stock: 0 },
      { skuKey: 'offal_liver_veal', name: 'كبدة بتلو صافي', isSource: true, price: 190, netPrice: 150, stock: 0 },
      { skuKey: 'offal_boush_veal', name: 'بوش بتلو', isSource: true, price: 140, netPrice: 100, stock: 0 },
      { skuKey: 'offal_bone_veal', name: 'عظم بتلو', isSource: true, price: 25, netPrice: 10, stock: 0 },
      { skuKey: 'offal_bone_kandouz', name: 'عظم كندوز', isSource: true, price: 20, netPrice: 8, stock: 0 },
      { skuKey: 'offal_giblets', name: 'كبد وقوانص', isSource: true, price: 70, netPrice: 45, stock: 0 },
      { skuKey: 'offal_chicken_liver', name: 'كبدة فراخ', isSource: true, price: 80, netPrice: 55, stock: 0 },
    ],
  },
  {
    code: 'FARM',
    name: 'المزرعة',
    sellByWeight: false,
    products: [
      { skuKey: 'farm_barqi_sheep', name: 'خروف برقي', productType: 'farm', price: 4500, netPrice: 3800, stock: 0 },
      { skuKey: 'farm_baladi_sheep', name: 'خروف بلدي', productType: 'farm', price: 4800, netPrice: 4000, stock: 0 },
      { skuKey: 'farm_beef_calf', name: 'عجل بقري', productType: 'farm', price: 28000, netPrice: 24000, stock: 0 },
      { skuKey: 'farm_buffalo_calf', name: 'عجل جاموسي', productType: 'farm', price: 27000, netPrice: 23000, stock: 0 },
      { skuKey: 'farm_veal', name: 'بتلو حي', productType: 'farm', price: 18000, netPrice: 15000, stock: 0 },
      { skuKey: 'farm_baladi_goat', name: 'جدي بلدي', productType: 'farm', price: 3500, netPrice: 2900, stock: 0 },
      { skuKey: 'farm_barqi_goat', name: 'جدي برقي', productType: 'farm', price: 3200, netPrice: 2700, stock: 0 },
    ],
  },
  {
    code: 'SERV',
    name: 'الخدمات',
    sellByWeight: false,
    products: [
      { skuKey: 'svc_slaughter_calf', name: 'ذبح عجل', productType: 'service', price: 250, netPrice: 0, stock: 0 },
      { skuKey: 'svc_slaughter_sheep', name: 'ذبح خروف', productType: 'service', price: 80, netPrice: 0, stock: 0 },
      { skuKey: 'svc_transport_calf', name: 'نقل عجل', productType: 'service', price: 150, netPrice: 0, stock: 0 },
      { skuKey: 'svc_transport_sheep', name: 'نقل خروف', productType: 'service', price: 50, netPrice: 0, stock: 0 },
      { skuKey: 'svc_process_meat', name: 'توضيب لحمة', productType: 'service', price: 20, netPrice: 0, stock: 0 },
      { skuKey: 'svc_grind', name: 'فرم لحمة', productType: 'service', price: 15, netPrice: 0, stock: 0 },
      { skuKey: 'svc_sausage_make', name: 'تصنيع سجق', productType: 'service', price: 25, netPrice: 0, stock: 0 },
      { skuKey: 'svc_cook_meat', name: 'تسوية لحم', productType: 'service', price: 40, netPrice: 0, stock: 0 },
      { skuKey: 'svc_rice_white', name: 'وجبة رز أبيض', productType: 'service', price: 25, netPrice: 0, stock: 0 },
      { skuKey: 'svc_rice_basmati', name: 'وجبة رز بسمتي', productType: 'service', price: 40, netPrice: 0, stock: 0 },
      { skuKey: 'svc_rice_tray', name: 'صينية رز بسمتي', productType: 'service', price: 180, netPrice: 0, stock: 0 },
    ],
  },
  {
    code: 'HONEY',
    name: 'عسل',
    sellByWeight: false,
    products: [
      piece('عسل زهور', { skuKey: 'honey_flower', price: 120, netPrice: 80 }),
      piece('عسل مكسرات', { skuKey: 'honey_nuts', price: 150, netPrice: 100 }),
      piece('عسل مكسرات نص', { skuKey: 'honey_nuts_half', price: 80, netPrice: 55 }),
      piece('عسل زهرة البرسيم', { skuKey: 'honey_clover', price: 130, netPrice: 90 }),
      piece('عسل موالح', { skuKey: 'honey_citrus', price: 125, netPrice: 85 }),
      piece('عسل تين شوكي', { skuKey: 'honey_prickly', price: 140, netPrice: 95 }),
      piece('عسل سدر جبلي', { skuKey: 'honey_sidr', price: 200, netPrice: 140 }),
      piece('عسل حبة البركة', { skuKey: 'honey_blackseed', price: 160, netPrice: 110 }),
      piece('عسل بردقوش', { skuKey: 'honey_marjoram', price: 150, netPrice: 100 }),
      piece('عسل شمر', { skuKey: 'honey_fennel', price: 145, netPrice: 98 }),
    ],
  },
  {
    code: 'DAIRY',
    name: 'ألبان ومؤن',
    sellByWeight: false,
    products: [
      piece('بيض بلدي', { skuKey: 'dairy_eggs_baladi', price: 8, netPrice: 5, stock: 0 }),
      piece('بيض أحمر وأبيض', { skuKey: 'dairy_eggs', price: 6, netPrice: 4, stock: 0 }),
      kg('حليب طبيعي', { skuKey: 'dairy_milk', sellByWeightOverride: true, price: 30, netPrice: 22, stock: 0 }),
      kg('زيت زيتون بكر ممتاز', { skuKey: 'dairy_olive', sellByWeightOverride: true, price: 180, netPrice: 130, stock: 0 }),
      kg('زبدة بلدي', { skuKey: 'dairy_butter', sellByWeightOverride: true, price: 160, netPrice: 120, stock: 0 }),
    ],
  },
];

const beefOffal = [
  { skuKey: 'kandouz_fridge', kind: 'fridge', label: 'كندوز ثلاجة' },
  { skuKey: 'offal_liver_kandouz', kind: 'offal', label: 'كبدة كندوز صافي' },
  { skuKey: 'offal_liver_mixed', kind: 'offal', label: 'كبدة كندوز مشكلة' },
  { skuKey: 'offal_heart', kind: 'offal', label: 'قلب كندوز' },
  { skuKey: 'offal_kidney', kind: 'offal', label: 'كلاوي كندوز' },
  { skuKey: 'offal_testicles', kind: 'offal', label: 'مخاصي' },
  { skuKey: 'offal_trotter_front', kind: 'offal', label: 'كوارع كندوز أمامي' },
  { skuKey: 'offal_trotter', kind: 'offal', label: 'كوارع كندوز' },
  { skuKey: 'offal_mombar', kind: 'offal', label: 'ممبار بلدي' },
  { skuKey: 'offal_tripe', kind: 'offal', label: 'كرشة' },
  { skuKey: 'offal_lung', kind: 'offal', label: 'فشة' },
  { skuKey: 'offal_spleen', kind: 'offal', label: 'طحال' },
  { skuKey: 'offal_head_meat', kind: 'offal', label: 'لحم راس' },
  { skuKey: 'offal_casing', kind: 'offal', label: 'هانك سجق' },
  { skuKey: 'offal_bone_kandouz', kind: 'offal', label: 'عظم كندوز' },
];

const lambOffal = [
  { skuKey: 'dhani_fridge', kind: 'fridge', label: 'ضاني ثلاجة' },
  { skuKey: 'offal_liver_lamb', kind: 'offal', label: 'كبدة ضاني' },
  { skuKey: 'offal_lamb_head', kind: 'offal', label: 'رأس ضاني' },
  { skuKey: 'offal_leya', kind: 'offal', label: 'لية ضاني' },
  { skuKey: 'offal_caul', kind: 'offal', label: 'منديل طرب' },
  { skuKey: 'offal_boush_lamb', kind: 'offal', label: 'بوش ضاني' },
  { skuKey: 'offal_bone_lamb', kind: 'offal', label: 'عظم ضاني' },
  { skuKey: 'offal_mombar', kind: 'offal', label: 'ممبار بلدي' },
];

export const AL_RAJI_SLAUGHTER_TEMPLATES = [
  {
    code: 'BEEF',
    name: 'عجل بقري',
    farmSkuKey: 'farm_beef_calf',
    outputs: beefOffal,
  },
  {
    code: 'BUFFALO',
    name: 'عجل جاموسي',
    farmSkuKey: 'farm_buffalo_calf',
    /** Same fridge/offal base as beef; buffalo-specific trotter included. */
    outputs: [
      ...beefOffal,
      { skuKey: 'offal_trotter_buffalo', kind: 'offal', label: 'كوارع جاموسي' },
    ],
  },
  {
    code: 'VEAL',
    name: 'بتلو',
    farmSkuKey: 'farm_veal',
    outputs: [
      { skuKey: 'betlo_fridge', kind: 'fridge', label: 'بتلو ثلاجة' },
      { skuKey: 'offal_liver_veal', kind: 'offal', label: 'كبدة بتلو صافي' },
      { skuKey: 'offal_boush_veal', kind: 'offal', label: 'بوش بتلو' },
      { skuKey: 'offal_bone_veal', kind: 'offal', label: 'عظم بتلو' },
    ],
  },
  {
    code: 'LAMB_BALADI',
    name: 'خروف بلدي',
    farmSkuKey: 'farm_baladi_sheep',
    outputs: lambOffal,
  },
  {
    code: 'LAMB_BARQI',
    name: 'خروف برقي',
    farmSkuKey: 'farm_barqi_sheep',
    outputs: lambOffal,
  },
  {
    code: 'GOAT_BALADI',
    name: 'جدي بلدي',
    farmSkuKey: 'farm_baladi_goat',
    outputs: lambOffal,
  },
  {
    code: 'GOAT_BARQI',
    name: 'جدي برقي',
    farmSkuKey: 'farm_barqi_goat',
    outputs: lambOffal,
  },
];
