/** Demo catalog for Egyptian large supermarket (Arabic names, EGP). */

export const DEMO_STORE = {
  storeName: 'سوبرماركت النيل',
  storePhoneNumber: '0227654321',
  receiptLanguage: 'ar',
  weightSalesEnabled: true,
  deliveryOrdersEnabled: true,
  cashierPurchaseExchangeEnabled: false,
};

/** Fixed monthly costs sized so demo daily trading profit stays green except the 15th. */
export const DEMO_BRANCHES = [
  {
    key: 'maadi',
    name: 'فرع المعادي',
    storeAddress: 'شارع 9، المعادي، القاهرة',
    rent: 9000,
    employeesSalary: 24000,
    branchInvoices: 1600,
    expenses: 1200,
    salespeople: ['أحمد سيد', 'محمود حسن', 'سارة علي'],
    deliveryStaff: ['محمد الدليفري', 'خالد توصيل', 'يoussef شحن'],
  },
  {
    key: 'nasr',
    name: 'فرع مدينة نصر',
    storeAddress: 'شارع عباس العقاد، مدينة نصر، القاهرة',
    rent: 10000,
    employeesSalary: 26000,
    branchInvoices: 1800,
    expenses: 1400,
    salespeople: ['كريم يoussef', 'نورا إبراهيم', 'ياسmin فتحي'],
    deliveryStaff: ['حسام دليفري', 'إبراهيم توصيل'],
  },
  {
    key: 'zayed',
    name: 'فرع الشيخ زايد',
    storeAddress: 'المحور المركزي، الشيخ زايد، الجيزة',
    rent: 9500,
    employeesSalary: 25000,
    branchInvoices: 1700,
    expenses: 1300,
    salespeople: ['عمر خالد', 'مariam نabil', 'تامر رضا'],
    deliveryStaff: ['أمير توصيل', 'سامي دليفري'],
  },
];

export const DEMO_USERS = [
  {
    name: 'مدير النظام',
    email: 'admin@nilesupermarket.demo',
    password: 'Demo1234!',
    role: 'Super Admin',
    locale: 'ar',
  },
  {
    name: 'كاشير المعادي',
    email: 'cashier.maadi@nilesupermarket.demo',
    password: 'Demo1234!',
    role: 'Cashier',
    locale: 'ar',
    branchKey: 'maadi',
  },
  {
    name: 'كاشير مدينة نصر',
    email: 'cashier.nasr@nilesupermarket.demo',
    password: 'Demo1234!',
    role: 'Cashier',
    locale: 'ar',
    branchKey: 'nasr',
  },
];

export const DEMO_CATEGORIES = [
  {
    code: 'MEAT',
    name: 'لحوم',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { name: 'لحم بقري بلدي', price: 320, netPrice: 285, stock: 120 },
      { name: 'لحم ضان', price: 380, netPrice: 340, stock: 45 },
      { name: 'لحم مفروم', price: 310, netPrice: 275, stock: 80 },
      { name: 'كبدة بقري', price: 180, netPrice: 155, stock: 35 },
      { name: 'مخ', price: 95, netPrice: 80, stock: 25 },
      { name: 'ريش ضاني', price: 420, netPrice: 375, stock: 30 },
      { name: 'موزة ضاني', price: 450, netPrice: 400, stock: 28 },
      { name: 'لحم جملي', price: 290, netPrice: 255, stock: 55 },
    ],
  },
  {
    code: 'POULTRY',
    name: 'دواجن',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { name: 'فراخ بلدي', price: 95, netPrice: 82, stock: 200 },
      { name: 'فراخ مجمدة', price: 78, netPrice: 68, stock: 150 },
      { name: 'صدور دجاج', price: 145, netPrice: 125, stock: 90 },
      { name: 'أوراك دجاج', price: 110, netPrice: 95, stock: 75 },
      { name: 'أجنحة دجاج', price: 85, netPrice: 72, stock: 60 },
      { name: 'رقبة دجاج', price: 55, netPrice: 45, stock: 40 },
      { name: 'كتاكيت', price: 88, netPrice: 75, stock: 65 },
    ],
  },
  {
    code: 'FISH',
    name: 'أسماك',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { name: 'بلطي طازج', price: 75, netPrice: 62, stock: 100 },
      { name: 'مكرونة سمك', price: 95, netPrice: 80, stock: 55 },
      { name: 'قاروص', price: 220, netPrice: 190, stock: 25 },
      { name: 'دنيس', price: 180, netPrice: 155, stock: 30 },
      { name: 'جمبري', price: 350, netPrice: 310, stock: 20 },
      { name: 'كalamari', price: 280, netPrice: 245, stock: 18 },
      { name: 'سردين طازج', price: 65, netPrice: 52, stock: 45 },
      { name: 'تونة طازجة', price: 160, netPrice: 135, stock: 22 },
    ],
  },
  {
    code: 'VEG',
    name: 'خضار',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { name: 'طماطم', price: 18, netPrice: 12, stock: 250 },
      { name: 'بطاطس', price: 15, netPrice: 10, stock: 400 },
      { name: 'بصل', price: 12, netPrice: 8, stock: 300 },
      { name: 'ثوم', price: 85, netPrice: 70, stock: 80 },
      { name: 'خيار', price: 16, netPrice: 11, stock: 120 },
      { name: 'فلفل ألوان', price: 35, netPrice: 25, stock: 90 },
      { name: 'كوسة', price: 22, netPrice: 15, stock: 70 },
      { name: 'باذنجان', price: 20, netPrice: 14, stock: 85 },
      { name: 'جزر', price: 18, netPrice: 12, stock: 110 },
      { name: 'سبانخ', price: 12, netPrice: 8, stock: 60 },
    ],
  },
  {
    code: 'FRUIT',
    name: 'فواكه',
    sellByWeight: true,
    weightUnit: 'kg',
    products: [
      { name: 'موز', price: 28, netPrice: 20, stock: 180 },
      { name: 'تفاح', price: 45, netPrice: 35, stock: 120 },
      { name: 'برتقال', price: 22, netPrice: 15, stock: 150 },
      { name: 'مانجو', price: 55, netPrice: 42, stock: 90 },
      { name: 'عنب', price: 48, netPrice: 38, stock: 70 },
      { name: 'فراولة', price: 65, netPrice: 50, stock: 40 },
      { name: 'بطيخ', price: 12, netPrice: 8, stock: 200 },
      { name: 'شمام', price: 18, netPrice: 12, stock: 100 },
      { name: 'كمثرى', price: 42, netPrice: 32, stock: 55 },
    ],
  },
  {
    code: 'DAIRY',
    name: 'ألبان وجبن',
    sellByWeight: false,
    products: [
      { name: 'لبن جهينة 1 لتر', price: 32, netPrice: 28, stock: 400 },
      { name: 'لبن لاكتيل 1 لتر', price: 30, netPrice: 26, stock: 350 },
      { name: 'زبادي دانون', price: 8, netPrice: 6, stock: 500 },
      { name: 'جبنة رومي', price: 185, netPrice: 160, stock: 80 },
      { name: 'جبنة قريش', price: 45, netPrice: 38, stock: 120 },
      { name: 'زبدة بلدي 500g', price: 95, netPrice: 82, stock: 90 },
      { name: 'كريمة طهي', price: 28, netPrice: 22, stock: 150 },
      { name: 'جبنة موزارella', price: 55, netPrice: 45, stock: 100 },
    ],
  },
  {
    code: 'BAKERY',
    name: 'مخبوزات',
    sellByWeight: false,
    products: [
      { name: 'عيش بلدي', price: 2, netPrice: 1.5, stock: 800 },
      { name: 'عيش فينو', price: 3, netPrice: 2.2, stock: 600 },
      { name: 'كرواسون', price: 12, netPrice: 8, stock: 200 },
      { name: 'توست هاينز', price: 28, netPrice: 22, stock: 150 },
      { name: 'كAKE شokolata', price: 35, netPrice: 28, stock: 80 },
      { name: 'دونات', price: 8, netPrice: 5, stock: 120 },
    ],
  },
  {
    code: 'DRINKS',
    name: 'مشروبات',
    sellByWeight: false,
    products: [
      { name: 'كوكا كola 1.5L', price: 18, netPrice: 14, stock: 500 },
      { name: 'بepsi 1.5L', price: 18, netPrice: 14, stock: 480 },
      { name: 'سprite 1.5L', price: 18, netPrice: 14, stock: 420 },
      { name: 'مياh Nestle 1.5L', price: 9, netPrice: 7, stock: 600 },
      { name: 'عصير جهina برtقال 1L', price: 22, netPrice: 18, stock: 300 },
      { name: 'شاي lipton 100 ظرف', price: 85, netPrice: 72, stock: 120 },
      { name: 'نسcafe gold', price: 195, netPrice: 170, stock: 80 },
      { name: 'Red Bull', price: 45, netPrice: 38, stock: 200 },
    ],
  },
  {
    code: 'CANNED',
    name: 'معلبات',
    sellByWeight: false,
    products: [
      { name: 'تUNA light 185g', price: 42, netPrice: 35, stock: 250 },
      { name: 'فول مdammas', price: 12, netPrice: 9, stock: 400 },
      { name: 'حمص مسلوق', price: 14, netPrice: 11, stock: 350 },
      { name: 'صلصة tomate 400g', price: 18, netPrice: 14, stock: 300 },
      { name: 'ذرة hulina', price: 22, netPrice: 18, stock: 280 },
      { name: 'زيتON اسpanish', price: 65, netPrice: 52, stock: 150 },
      { name: 'عسل nahl 500g', price: 120, netPrice: 95, stock: 60 },
    ],
  },
  {
    code: 'CLEAN',
    name: 'منظفات',
    sellByWeight: false,
    products: [
      { name: 'persil 4kg', price: 185, netPrice: 155, stock: 120 },
      { name: 'OMO 3kg', price: 165, netPrice: 140, stock: 100 },
      { name: 'fairy lemon 1L', price: 55, netPrice: 45, stock: 180 },
      { name: 'dettol معقم 750ml', price: 48, netPrice: 38, stock: 150 },
      { name: 'مناديل kitchen', price: 28, netPrice: 22, stock: 200 },
      { name: 'bleach كلorox', price: 22, netPrice: 17, stock: 160 },
      { name: 'سائل أرضيات', price: 35, netPrice: 28, stock: 140 },
    ],
  },
  {
    code: 'RICE',
    name: 'أرز وحبوب',
    sellByWeight: false,
    products: [
      { name: 'أرز مصري 5kg', price: 95, netPrice: 82, stock: 300 },
      { name: 'أرز basmati 5kg', price: 185, netPrice: 160, stock: 150 },
      { name: 'عدس أصفر 1kg', price: 35, netPrice: 28, stock: 200 },
      { name: 'فاصolia بيضاء 1kg', price: 42, netPrice: 35, stock: 180 },
      { name: 'حمص جاف 1kg', price: 38, netPrice: 30, stock: 160 },
      { name: 'شوفan 500g', price: 22, netPrice: 17, stock: 220 },
    ],
  },
  {
    code: 'PASTA',
    name: 'مكرونة ونشويات',
    sellByWeight: false,
    products: [
      { name: 'مكرونة regina 500g', price: 18, netPrice: 14, stock: 400 },
      { name: 'مكرونة penne', price: 20, netPrice: 16, stock: 350 },
      { name: 'شعيرية 500g', price: 15, netPrice: 12, stock: 300 },
      { name: 'lasagna sheets', price: 28, netPrice: 22, stock: 120 },
      { name: 'corn flakes nestle', price: 65, netPrice: 52, stock: 100 },
    ],
  },
  {
    code: 'SPICE',
    name: 'بهارات',
    sellByWeight: false,
    products: [
      { name: 'ملح iodized 1kg', price: 8, netPrice: 5, stock: 500 },
      { name: 'فلفل أسود', price: 35, netPrice: 28, stock: 150 },
      { name: 'كمون', price: 42, netPrice: 35, stock: 140 },
      { name: 'كركم', price: 38, netPrice: 30, stock: 130 },
      { name: 'بهارات مشكلة', price: 45, netPrice: 38, stock: 120 },
      { name: 'قرفة', price: 55, netPrice: 45, stock: 90 },
    ],
  },
  {
    code: 'SNACKS',
    name: 'حلويات وسناكس',
    sellByWeight: false,
    products: [
      { name: 'chipsy cheese', price: 12, netPrice: 9, stock: 450 },
      { name: 'doritos nacho', price: 15, netPrice: 11, stock: 380 },
      { name: 'biscuit oreo', price: 18, netPrice: 14, stock: 320 },
      { name: 'Galaxy chocolate', price: 25, netPrice: 20, stock: 280 },
      { name: 'كatakito', price: 8, netPrice: 6, stock: 400 },
      { name: 'pop corn', price: 10, netPrice: 7, stock: 200 },
    ],
  },
  {
    code: 'BABY',
    name: 'منتجات أطفال',
    sellByWeight: false,
    products: [
      { name: 'حليب similac 1', price: 285, netPrice: 250, stock: 80 },
      { name: 'حفاضات pampers 4', price: 195, netPrice: 170, stock: 100 },
      { name: 'مناديل wet wipes', price: 45, netPrice: 38, stock: 150 },
      { name: 'shampoo johnson', price: 55, netPrice: 45, stock: 120 },
    ],
  },
  {
    code: 'PERSONAL',
    name: 'عناية شخصية',
    sellByWeight: false,
    products: [
      { name: 'shampoo head&shoulders', price: 95, netPrice: 78, stock: 140 },
      { name: 'toothpaste colgate', price: 42, netPrice: 35, stock: 200 },
      { name: 'deodorant axe', price: 75, netPrice: 62, stock: 160 },
      { name: 'soap lux', price: 18, netPrice: 14, stock: 250 },
      { name: 'shaving gillette', price: 85, netPrice: 70, stock: 100 },
    ],
  },
  {
    code: 'FROZEN',
    name: 'مجمدات',
    sellByWeight: false,
    products: [
      { name: 'بطاطس McCain 2.5kg', price: 125, netPrice: 105, stock: 90 },
      { name: 'nuggets 1kg', price: 95, netPrice: 80, stock: 110 },
      { name: 'بizza margherita', price: 65, netPrice: 52, stock: 80 },
      { name: 'آيس cream magnum', price: 35, netPrice: 28, stock: 150 },
      { name: 'خضار mixed frozen 1kg', price: 45, netPrice: 36, stock: 100 },
    ],
  },
];

export const DEMO_CLIENTS = [
  { name: 'محمد عبدالله', phone: '01001234567', address: 'المعادي، القاهرة' },
  { name: 'فاطمة حسين', phone: '01002345678', address: 'مدينة نصر' },
  { name: 'أحمد محmoud', phone: '01003456789', address: 'الشيخ زايد' },
  { name: 'نورhan سami', phone: '01004567890', address: 'التجمع الخامس' },
  { name: 'خالد عمر', phone: '01005678901', address: 'المعادي' },
  { name: 'مariam أحمد', phone: '01006789012', address: 'حلوان' },
  { name: 'يoussef إبراهim', phone: '01007890123', address: 'مدينة نصر' },
  { name: 'هبة محمد', phone: '01008901234', address: '6 أكتوبر' },
  { name: 'عبدالرحman علي', phone: '01009012345', address: 'المعادي' },
  { name: 'سلma Hassan', phone: '01101234567', address: 'الزمالك' },
  { name: 'كريم ناصر', phone: '01102345678', address: 'مدينة نصر' },
  { name: 'دina Sameh', phone: '01103456789', address: 'الشيخ زايد' },
  { name: 'طarek فؤاد', phone: '01104567890', address: 'المعادي' },
  { name: 'rania Adel', phone: '01105678901', address: 'مصر الجديدة' },
  { name: 'waleed Samir', phone: '01106789012', address: 'الشيخ زايد' },
  { name: 'esraa Hany', phone: '01107890123', address: 'مدينة نصر' },
  { name: 'hassan Magdy', phone: '01108901234', address: 'المعادي' },
  { name: 'menna Ashraf', phone: '01109012345', address: 'التجمع' },
  { name: 'amr Tarek', phone: '01201234567', address: '6 أكتوبر' },
  { name: 'laila Karim', phone: '01202345678', address: 'الشيخ زايد' },
  { name: 'sherif Nabil', phone: '01203456789', address: 'مدينة نصر' },
  { name: 'nada Emad', phone: '01204567890', address: 'المعادي' },
  { name: 'omar Hossam', phone: '01205678901', address: 'حلوان' },
  { name: 'yasmin Atef', phone: '01206789012', address: 'الشيخ زايد' },
  { name: 'mohamed Saeed', phone: '01207890123', address: 'مدينة نصر' },
  { name: 'hoda Ramadan', phone: '01208901234', address: 'المعادي' },
  { name: 'ali Fawzy', phone: '01209012345', address: 'التجمع' },
  { name: 'reem Walid', phone: '01501234567', address: '6 أكتوبر' },
  { name: 'hany Lotfy', phone: '01502345678', address: 'الشيخ زايد' },
  { name: 'samar Reda', phone: '01503456789', address: 'مدينة نصر' },
  { name: 'ehab Mostafa', phone: '01504567890', address: 'المعادي' },
  { name: 'ghada Khaled', phone: '01505678901', address: 'مصر الجديدة' },
  { name: 'tamer Fouad', phone: '01506789012', address: 'الشيخ زايد' },
  { name: 'noha Said', phone: '01507890123', address: 'مدينة نصر' },
  { name: 'bassem Adel', phone: '01508901234', address: 'المعادي' },
  { name: 'dalia Hesham', phone: '01509012345', address: 'التجمع' },
  { name: 'moustafa Gamal', phone: '01011234567', address: '6 أكتوبر' },
  { name: 'heba Anwar', phone: '01012345678', address: 'الشيخ زايد' },
  { name: 'reda Salah', phone: '01013456789', address: 'مدينة نصر' },
  { name: 'amira Zaki', phone: '01014567890', address: 'المعادي' },
  { name: 'عميل نقدي', phone: '01000000001', address: '—' },
  { name: 'عميل نقدي 2', phone: '01000000002', address: '—' },
  { name: 'شركة catering', phone: '01000000003', address: 'التجمع الخامس' },
  { name: 'مطعm delivery', phone: '01000000004', address: 'مدينة نصر' },
  { name: 'كafeteria مدرسة', phone: '01000000005', address: 'المعادي' },
  { name: 'بيت zyara', phone: '01000000006', address: 'الشيخ زايد' },
  { name: 'سكن طلab', phone: '01000000007', address: 'مدينة نصر' },
  { name: 'عائلة كبيرة', phone: '01000000008', address: '6 أكتوبر' },
  { name: 'جiran', phone: '01000000009', address: 'المعادي' },
  { name: 'عميل VIP', phone: '01000000010', address: 'الزمالك' },
];

export const DEMO_VENDORS = [
  {
    nameOfcompany: 'شركة اللحوم الذهبية',
    name: 'أ/ سامح رagab',
    phone: '0223456789',
    email: 'sales@goldmeat.eg',
    paymentTerms: ['cash'],
    categoryCodes: ['MEAT'],
  },
  {
    nameOfcompany: 'مزارع الدواجن الحديثة',
    name: 'أ/ هشam fouad',
    phone: '0224567890',
    email: 'orders@modernpoultry.eg',
    paymentTerms: ['Deferred'],
    categoryCodes: ['POULTRY'],
  },
  {
    nameOfcompany: 'أسماك البحر الأحمر',
    name: 'captain mohamed',
    phone: '0225678901',
    email: 'fish@redsea.eg',
    paymentTerms: ['cash'],
    categoryCodes: ['FISH'],
  },
  {
    nameOfcompany: 'خضار delta fresh',
    name: 'أ/ ramy saad',
    phone: '0226789012',
    email: 'supply@deltafresh.eg',
    paymentTerms: ['cash'],
    categoryCodes: ['VEG', 'FRUIT'],
  },
  {
    nameOfcompany: 'جهina للألبان',
    name: 'ممثل مبيعات',
    phone: '0227890123',
    email: 'b2b@juhayna.com',
    paymentTerms: ['Deferred'],
    categoryCodes: ['DAIRY'],
  },
  {
    nameOfcompany: 'unilever مصر',
    name: 'أ/ khaled nabil',
    phone: '0228901234',
    email: 'trade@unilever.eg',
    paymentTerms: ['Installments'],
    categoryCodes: ['CLEAN', 'PERSONAL'],
  },
  {
    nameOfcompany: 'nestle waters',
    name: 'sales rep',
    phone: '0229012345',
    email: 'orders@nestle.eg',
    paymentTerms: ['Deferred'],
    categoryCodes: ['DRINKS'],
  },
  {
    nameOfcompany: 'heinz & general foods',
    name: 'أ/ wael adel',
    phone: '0230123456',
    email: 'heinz@supply.eg',
    paymentTerms: ['cash'],
    categoryCodes: ['CANNED', 'SPICE'],
  },
  {
    nameOfcompany: 'السكر والأرز الوطني',
    name: 'أ/ tarek lotfy',
    phone: '0231234567',
    email: 'rice@national.eg',
    paymentTerms: ['cash'],
    categoryCodes: ['RICE', 'PASTA'],
  },
  {
    nameOfcompany: 'مخبز automatic',
    name: 'أ/ sameh',
    phone: '0232345678',
    email: 'bakery@auto.eg',
    paymentTerms: ['cash'],
    categoryCodes: ['BAKERY'],
  },
  {
    nameOfcompany: 'cadbury & snacks co',
    name: 'rep snacks',
    phone: '0233456789',
    email: 'snacks@cadbury.eg',
    paymentTerms: ['Deferred'],
    categoryCodes: ['SNACKS'],
  },
  {
    nameOfcompany: 'pampers distributor',
    name: 'أ/ nader',
    phone: '0234567890',
    email: 'baby@pampers.eg',
    paymentTerms: ['Installments'],
    categoryCodes: ['BABY'],
  },
  {
    nameOfcompany: 'McCain frozen',
    name: 'cold chain sales',
    phone: '0235678901',
    email: 'frozen@mccain.eg',
    paymentTerms: ['Deferred'],
    categoryCodes: ['FROZEN'],
  },
  {
    nameOfcompany: 'توريدات general',
    name: 'أ/ ashraf',
    phone: '0236789012',
    email: 'general@supply.eg',
    paymentTerms: ['cash'],
    categoryCodes: ['DRINKS', 'CANNED', 'CLEAN'],
  },
  {
    nameOfcompany: 'farm to table',
    name: 'أ/ mona',
    phone: '0237890123',
    email: 'farm@table.eg',
    paymentTerms: ['cash'],
    categoryCodes: ['VEG', 'FRUIT', 'MEAT'],
  },
];
